<a href="https://colab.research.google.com/github/Leo-Santos17/Big-Data_PowerFit/blob/dev/BigData_Academia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inicialização

In [ ]:
import pandas as pd
import tensorflow as tf
import sklearn
import numpy as np

In [ ]:
pd.__version__, sklearn.__version__, tf.__version__

('2.2.2', '1.6.1', '2.20.0')

In [ ]:
from tensorflow.keras.layers import Dense, Dropout, Activation, Input
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Model, Sequential
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from tensorflow.keras import utils as np_utils

In [ ]:
import gdown

# O link da pasta: https://drive.google.com/drive/folders/ID_DA_PASTA
folder_url = 'https://drive.google.com/drive/folders/136-2N-itYCWcALZGlLEEf0CTabmH7eQm'

# Baixa a pasta recursivamente
gdown.download_folder(folder_url, quiet=False, use_cookies=True)

Retrieving folder contents


Retrieving folder 14m_P_BugAAO4flyNJ4bv7-laxnRTKM_1 Base
Processing file 1Yg97ayXvprm_0KHmdays8nwFKJBC4R0c gym_members_dataset.csv
Processing file 1XXK0A2hceY4hzJ2hujQrhRPVQ3FVoDNM gym_membership.csv
Retrieving folder 1kEl7kLDJunvSCBQ41Kpu2SO0UY7ujomD Catraca
Processing file 174rVT6smt7sONx4o9SBHlieQ6C5UI121 Ago-Set.csv
Processing file 1tsjyhYeOj6jUTXzDG0USrwypixLi3HDY Dec-Jan.csv
Processing file 1ddc-aCeFCGOHsCk9eygui5nIDGA-Avqp Fev-Marc.csv
Processing file 1lHpwl-5RT9whH7VUob1fCY5U84FWCfg9 Jan-Fev.csv
Processing file 1JpSj2frqPqm7qW1w46VI9IRtXFaSgWoX Jul-Ago.csv
Processing file 1HmZ9NrHMGzWpx4d0NTTQI8mOipoP5j5_ Jun-Jul.csv
Processing file 1fO1bdh5a2w9F7N4a1UrKhIxXqAYj7i_z Mai-Jun.csv
Processing file 1yKaLEIw6UaaidLnnhQrhi4jhhQVPcAKc Mar-Abrl.csv
Processing file 1AuFIeOKB8rIUoS6iL4xACiYs5Xm6f3Ey Nov-Dec.csv
Processing file 1GDCUzWDTYzR8aXrJUXQnUTHiSzxCTgzh Outu-Nov.csv
Processing file 127huiyM8Lfz9WZC498-r4CMWtMc-Vd4M Set-Outu.csv
Retrieving folder 1i5m8K2FvL3xZkxUhnG9CXoQBWTmDSIu1 In

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1Yg97ayXvprm_0KHmdays8nwFKJBC4R0c
To: /content/BigData/Base/gym_members_dataset.csv
100%|██████████| 17.9k/17.9k [00:00<00:00, 24.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XXK0A2hceY4hzJ2hujQrhRPVQ3FVoDNM
To: /content/BigData/Base/gym_membership.csv
100%|██████████| 115k/115k [00:00<00:00, 1.58MB/s]
Downloading...
From: https://drive.google.com/uc?id=174rVT6smt7sONx4o9SBHlieQ6C5UI121
To: /content/BigData/Catraca/Ago-Set.csv
100%|██████████| 5.97k/5.97k [00:00<00:00, 5.33MB/s]
Downloading...
From: https://drive.google.com/uc?id=1tsjyhYeOj6jUTXzDG0USrwypixLi3HDY
To: /content/BigData/Catraca/Dec-Jan.csv
100%|██████████| 4.65k/4.65k [00:00<00:00, 17.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ddc-aCeFCGOHsCk9eygui5nIDGA-Avqp
To: /content/BigData/Catraca/Fev-Marc.csv
100%|██████████| 5.24k/5.24k [00:00<

['/content/BigData/Base/gym_members_dataset.csv',
 '/content/BigData/Base/gym_membership.csv',
 '/content/BigData/Catraca/Ago-Set.csv',
 '/content/BigData/Catraca/Dec-Jan.csv',
 '/content/BigData/Catraca/Fev-Marc.csv',
 '/content/BigData/Catraca/Jan-Fev.csv',
 '/content/BigData/Catraca/Jul-Ago.csv',
 '/content/BigData/Catraca/Jun-Jul.csv',
 '/content/BigData/Catraca/Mai-Jun.csv',
 '/content/BigData/Catraca/Mar-Abrl.csv',
 '/content/BigData/Catraca/Nov-Dec.csv',
 '/content/BigData/Catraca/Outu-Nov.csv',
 '/content/BigData/Catraca/Set-Outu.csv',
 '/content/BigData/Instrutor/Ago-Out.csv',
 '/content/BigData/Instrutor/Fev-Abr.csv',
 '/content/BigData/Instrutor/Mai-Jul.csv',
 '/content/BigData/Instrutor/Nov-Jan.csv',
 '/content/BigData/Presenca/Abri_2025.xlsx',
 '/content/BigData/Presenca/Ago-Outu.xlsx',
 '/content/BigData/Presenca/Fev-Abr.xlsx',
 '/content/BigData/Presenca/Mai-Jul.xlsx',
 '/content/BigData/Presenca/Nov-Jan.xlsx',
 '/content/BigData/Base-Clientes.csv',
 '/content/BigData/Cl

# Tratamento

In [ ]:
base = pd.read_csv('/content/BigData/Base/gym_members_dataset.csv')
base

,Member_ID,Name,Age,Gender,Address,Phone_Number,Membership_Type,Join_Date,Last_Visit_Date,Favorite_Exercise,Avg_Workout_Duration_Min,Avg_Calories_Burned,Total_Weight_Lifted_kg,Visits_Per_Month,Churn
0,1,NaN,19.0,Male,"Street 171, City 39",032-51510359,Quarterly,2022-07-23,2022-11-03,Pull-ups,93,214.0,13995.0,18.0,No
1,2,Shanza,19.0,Female,"Street 111, City 18",039-19243328,Monthly,2023-12-04,2024-02-14,Squats,37,436.0,4612.0,11.0,No
2,3,Ubaidullah,52.0,Male,"Street 69, City 21",033-60221501,Quarterly,2024-09-13,2024-12-07,Bench Press,98,523.0,3124.0,4.0,Yes
3,4,Mansoor Ahmed,52.0,Male,"Street 72, City 39",035-55527902,Monthly,2024-06-05,2025-02-24,Pull-ups,66,282.0,4586.0,24.0,No
4,5,Hanzala,32.0,Male,"Street 6, City 12",038-93946322,Monthly,2022-06-15,2022-12-02,Bench Press,32,522.0,16353.0,18.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,Mohammed,54.0,Male,"Street 2, City 15",036-24733357,Quarterly,2023-12-10,2024-04-27,Pull-ups,64,733.0,6082.0,14.0,No
146,147,Haseena,45.0,Female,"Street 31, City 22",038-73797777,Monthly,2023-02-10,2023-04-02,Bench Press,95,641.0,7375.0,12.0,No
147,148,Hassaan,54.0,Male,"Street 121, City 31",032-16612823,Quarterly,2023-03-27,2023-12-07,Deadlift,80,471.0,6138.0,14.0,No
148,149,Najat,26.0,Female,"Street 190, City 9",034-49625944,Monthly,2023-05-05,2024-03-26,Bench Press,50,473.0,18336.0,4.0,Yes


In [ ]:
base = base.drop('Last_Visit_Date', axis=1)
base = base.drop('Member_ID', axis=1)
base = base.drop('Name', axis=1)
base = base.drop('Address', axis=1)
base = base.drop('Phone_Number', axis=1)
base = base.drop('Membership_Type', axis=1)
base = base.drop('Join_Date', axis=1)
base = base.drop('Avg_Workout_Duration_Min', axis=1)
base = base.drop('Avg_Calories_Burned', axis=1)
base = base.drop('Total_Weight_Lifted_kg', axis=1)
base = base.drop('Visits_Per_Month', axis=1)
base = base.drop('Churn', axis=1)

In [ ]:
base.shape

(150, 3)

In [ ]:
valores = {
    "Age": 27
}

In [ ]:
base = base.fillna(value = valores)

## X e Y

In [ ]:
base.columns

Index(['Age', 'Gender', 'Favorite_Exercise'], dtype='object')

In [ ]:
X = base.iloc[:, [0,1]].values
X

array([[19.0, 'Male'],
       [19.0, 'Female'],
       [52.0, 'Male'],
       [52.0, 'Male'],
       [32.0, 'Male'],
       [53.0, 'Male'],
       [46.0, 'Male'],
       [36.0, 'Male'],
       [41.0, 'Male'],
       [27.0, 'Female'],
       [23.0, 'Male'],
       [22.0, 'Male'],
       [50.0, 'Female'],
       [22.0, 'Female'],
       [27.0, 'Male'],
       [49.0, 'Female'],
       [29.0, 'Male'],
       [36.0, 'Female'],
       [45.0, 'Male'],
       [28.0, 'Female'],
       [34.0, 'Female'],
       [39.0, 'Male'],
       [20.0, 'Female'],
       [27.0, 'Male'],
       [27.0, 'Female'],
       [39.0, 'Male'],
       [25.0, 'Female'],
       [29.0, 'Male'],
       [29.0, 'Male'],
       [27.0, 'Male'],
       [51.0, 'Female'],
       [27.0, 'Male'],
       [27.0, 'Female'],
       [54.0, 'Male'],
       [39.0, 'Male'],
       [47.0, 'Male'],
       [53.0, 'Female'],
       [44.0, 'Female'],
       [36.0, 'Female'],
       [51.0, 'Male'],
       [43.0, 'Male'],
       [44.0, 'Male'],
  

In [ ]:
Y = base.iloc[:, 2].values
Y

array(['Pull-ups', 'Squats', 'Bench Press', 'Pull-ups', 'Bench Press',
       'Deadlift', 'Squats', 'Deadlift', 'Squats', 'Pull-ups',
       'Bench Press', 'Deadlift', 'Squats', 'Treadmill', 'Treadmill',
       'Treadmill', 'Pull-ups', 'Squats', 'Deadlift', 'Squats', 'Cycling',
       'Treadmill', 'Pull-ups', 'Squats', 'Squats', 'Deadlift',
       'Pull-ups', 'Cycling', 'Treadmill', 'Treadmill', 'Treadmill',
       'Cycling', 'Bench Press', 'Squats', 'Squats', 'Bench Press',
       'Bench Press', 'Deadlift', 'Cycling', 'Deadlift', 'Pull-ups',
       'Treadmill', 'Deadlift', 'Cycling', 'Deadlift', 'Treadmill',
       'Pull-ups', 'Treadmill', 'Squats', 'Squats', 'Bench Press',
       'Treadmill', 'Bench Press', 'Squats', 'Squats', 'Deadlift',
       'Deadlift', 'Pull-ups', 'Pull-ups', 'Treadmill', 'Squats',
       'Treadmill', 'Deadlift', 'Deadlift', 'Treadmill', 'Deadlift',
       'Pull-ups', 'Cycling', 'Deadlift', 'Cycling', 'Bench Press',
       'Bench Press', 'Pull-ups', 'Deadlift', 

## Atribuição Numerica

In [ ]:
onehotencoder = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1])], remainder='passthrough')
X = onehotencoder.fit_transform(X)
X

array([[0.0, 1.0, 19.0],
       [1.0, 0.0, 19.0],
       [0.0, 1.0, 52.0],
       [0.0, 1.0, 52.0],
       [0.0, 1.0, 32.0],
       [0.0, 1.0, 53.0],
       [0.0, 1.0, 46.0],
       [0.0, 1.0, 36.0],
       [0.0, 1.0, 41.0],
       [1.0, 0.0, 27.0],
       [0.0, 1.0, 23.0],
       [0.0, 1.0, 22.0],
       [1.0, 0.0, 50.0],
       [1.0, 0.0, 22.0],
       [0.0, 1.0, 27.0],
       [1.0, 0.0, 49.0],
       [0.0, 1.0, 29.0],
       [1.0, 0.0, 36.0],
       [0.0, 1.0, 45.0],
       [1.0, 0.0, 28.0],
       [1.0, 0.0, 34.0],
       [0.0, 1.0, 39.0],
       [1.0, 0.0, 20.0],
       [0.0, 1.0, 27.0],
       [1.0, 0.0, 27.0],
       [0.0, 1.0, 39.0],
       [1.0, 0.0, 25.0],
       [0.0, 1.0, 29.0],
       [0.0, 1.0, 29.0],
       [0.0, 1.0, 27.0],
       [1.0, 0.0, 51.0],
       [0.0, 1.0, 27.0],
       [1.0, 0.0, 27.0],
       [0.0, 1.0, 54.0],
       [0.0, 1.0, 39.0],
       [0.0, 1.0, 47.0],
       [1.0, 0.0, 53.0],
       [1.0, 0.0, 44.0],
       [1.0, 0.0, 36.0],
       [0.0, 1.0, 51.0],


In [ ]:
X = np.array(X, dtype=np.float32)

In [ ]:
X

array([[ 0.,  1., 19.],
       [ 1.,  0., 19.],
       [ 0.,  1., 52.],
       [ 0.,  1., 52.],
       [ 0.,  1., 32.],
       [ 0.,  1., 53.],
       [ 0.,  1., 46.],
       [ 0.,  1., 36.],
       [ 0.,  1., 41.],
       [ 1.,  0., 27.],
       [ 0.,  1., 23.],
       [ 0.,  1., 22.],
       [ 1.,  0., 50.],
       [ 1.,  0., 22.],
       [ 0.,  1., 27.],
       [ 1.,  0., 49.],
       [ 0.,  1., 29.],
       [ 1.,  0., 36.],
       [ 0.,  1., 45.],
       [ 1.,  0., 28.],
       [ 1.,  0., 34.],
       [ 0.,  1., 39.],
       [ 1.,  0., 20.],
       [ 0.,  1., 27.],
       [ 1.,  0., 27.],
       [ 0.,  1., 39.],
       [ 1.,  0., 25.],
       [ 0.,  1., 29.],
       [ 0.,  1., 29.],
       [ 0.,  1., 27.],
       [ 1.,  0., 51.],
       [ 0.,  1., 27.],
       [ 1.,  0., 27.],
       [ 0.,  1., 54.],
       [ 0.,  1., 39.],
       [ 0.,  1., 47.],
       [ 1.,  0., 53.],
       [ 1.,  0., 44.],
       [ 1.,  0., 36.],
       [ 0.,  1., 51.],
       [ 0.,  1., 43.],
       [ 0.,  1.

In [ ]:
labelencoder = LabelEncoder()
Y = labelencoder.fit_transform(Y)
Y

array([3, 4, 0, 3, 0, 2, 4, 2, 4, 3, 0, 2, 4, 5, 5, 5, 3, 4, 2, 4, 1, 5,
       3, 4, 4, 2, 3, 1, 5, 5, 5, 1, 0, 4, 4, 0, 0, 2, 1, 2, 3, 5, 2, 1,
       2, 5, 3, 5, 4, 4, 0, 5, 0, 4, 4, 2, 2, 3, 3, 5, 4, 5, 2, 2, 5, 2,
       3, 1, 2, 1, 0, 0, 3, 2, 3, 2, 4, 0, 1, 5, 0, 4, 4, 5, 2, 4, 4, 1,
       0, 2, 3, 1, 2, 3, 3, 4, 0, 5, 5, 0, 2, 3, 0, 5, 2, 5, 0, 3, 4, 2,
       3, 0, 3, 4, 3, 1, 3, 5, 0, 0, 4, 0, 5, 3, 5, 1, 5, 5, 3, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 1, 0, 2, 0, 1, 4, 4, 3, 0, 2, 0, 4])

In [ ]:
Y = np_utils.to_categorical(Y)
Y

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0.

In [ ]:
X.shape, Y.shape

((150, 3), (150, 6))

## Divisão

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [ ]:
Y_test3 = Y_test

## Regressor

In [ ]:
X_train.shape, Y_train.shape

((135, 3), (135, 6))

In [ ]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(3,)),
    tf.keras.layers.Dense(units=5, activation='relu'),
    tf.keras.layers.Dense(units=5, activation='relu'),
    tf.keras.layers.Dense(units=6, activation='softmax')
])

In [ ]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 5)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 6)              │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 86 (344.00 B)

 Trainable params: 86 (344.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
rede_neural.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["categorical_accuracy"])

In [ ]:
rede_neural.fit(X_train, Y_train, batch_size=5, epochs=700)

Epoch 1/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - categorical_accuracy: 0.2000 - loss: 7.6382
Epoch 2/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 6.1550
Epoch 3/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 4.9691
Epoch 4/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 4.0221
Epoch 5/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 3.2722
Epoch 6/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 2.7210
Epoch 7/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.2000 - loss: 2.3172
Epoch 8/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 2.0907
Epoch 9/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 1.9734
Epoch 10/700
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2000 - loss: 1.9055
Epoch 11/700
27/27 ━━━━━━━━━━

# Testes

In [ ]:
previsoes = rede_neural.predict(X_test)
previsoes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step


array([[0.18466833, 0.09247559, 0.15680972, 0.20593883, 0.12166276,
        0.23844478],
       [0.21154284, 0.12072319, 0.16372834, 0.19131607, 0.18600138,
        0.12668814],
       [0.2003423 , 0.0967328 , 0.1880283 , 0.18829511, 0.20238492,
        0.12421664],
       [0.18466833, 0.09247559, 0.15680972, 0.20593883, 0.12166276,
        0.23844478],
       [0.13487938, 0.02919502, 0.319357  , 0.15248784, 0.26529688,
        0.09878384],
       [0.18466833, 0.09247559, 0.15680972, 0.20593883, 0.12166276,
        0.23844478],
       [0.14326337, 0.03428097, 0.30215588, 0.15826942, 0.25926805,
        0.10276232],
       [0.15740244, 0.04451646, 0.27376774, 0.1673247 , 0.24793491,
        0.10905378],
       [0.18498032, 0.08877128, 0.15833041, 0.20077997, 0.12584473,
        0.24129325],
       [0.18378332, 0.1002112 , 0.15359238, 0.21634829, 0.11354881,
        0.23251605],
       [0.18477559, 0.065823  , 0.16722174, 0.1659525 , 0.1573856 ,
        0.25884154],
       [0.17956023, 0

In [ ]:
previsoes = rede_neural.predict(X_test)
previsoes = previsoes > 0.2
previsoes

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[False, False, False,  True, False,  True],
       [ True, False, False, False, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False,  True, False,  True],
       [False, False,  True, False,  True, False],
       [False, False, False,  True, False,  True],
       [False, False,  True, False,  True, False],
       [False, False,  True, False,  True, False],
       [False, False, False,  True, False,  True],
       [False, False, False,  True, False,  True],
       [False, False, False, False, False,  True],
       [False, False, False,  True, False,  True],
       [ True, False, False, False,  True, False],
       [False, False, False, False, False,  True],
       [False, False,  True, False,  True, False]])

In [ ]:
Y_test3

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.]])

In [ ]:
y_pred2 = [np.argmax(t) for t in previsoes]
y_pred2

[np.int64(3),
 np.int64(0),
 np.int64(0),
 np.int64(3),
 np.int64(2),
 np.int64(3),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(3),
 np.int64(5),
 np.int64(3),
 np.int64(0),
 np.int64(5),
 np.int64(2)]